site_name: Irpf
site_description: Documentation for Irpf
repo_url: https://github.com/guilhermegor/irpf
nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: api.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
