"""Domain entities and helpers for serialization and identifiers."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from typing import Any
import uuid

Record = dict[str, Any]


@dataclass
class BaseEntity:
    """Base entity with an autogenerated identifier and serialization helper.

    Attributes
    ----------
    id : str
        Unique identifier assigned at instantiation time.
    """

    id: str = field(default_factory=lambda: uuid.uuid4().hex)

    def to_record(self) -> Record:
        """Convert the entity to a plain record.

        Returns
        -------
        Record
            Dictionary representation suitable for persistence.
        """

        return asdict(self)
