"""alter_posicao_integer_to_numeric

Revision ID: 86053cd8b1f8
Revises: 8ef63ada69a6
Create Date: 2026-05-25 15:00:22.465369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86053cd8b1f8'
down_revision: Union[str, Sequence[str], None] = '8ef63ada69a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('b3_posicao_acoes', 'conta',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade_disp',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade_indisp',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=True)
    op.alter_column('b3_posicao_emprestimos', 'quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=18, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('b3_posicao_emprestimos', 'quantidade',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade_indisp',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade_disp',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'quantidade',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('b3_posicao_acoes', 'conta',
               existing_type=sa.Numeric(precision=18, scale=0),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
