"""create_b3_tables

Revision ID: 7b98ce6f574f
Revises:
Create Date: 2026-05-25 14:54:28.034454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b98ce6f574f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b3_bonificacao_acoes',
    sa.Column('pk_movimentacao', sa.String(length=600), nullable=False),
    sa.Column('entrada_saida', sa.String(length=100), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.Column('movimentacao', sa.String(length=200), nullable=True),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_operacao', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('pk_movimentacao')
    )
    op.create_table('b3_movimentacao',
    sa.Column('pk_movimentacao', sa.String(length=600), nullable=False),
    sa.Column('entrada_saida', sa.String(length=100), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.Column('movimentacao', sa.String(length=200), nullable=True),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_operacao', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('pk_movimentacao')
    )
    op.create_table('b3_negociacao',
    sa.Column('pk_negociacao', sa.String(length=600), nullable=False),
    sa.Column('data_negocio', sa.Date(), nullable=True),
    sa.Column('tipo_movimentacao', sa.String(length=100), nullable=True),
    sa.Column('mercado', sa.String(length=100), nullable=True),
    sa.Column('prazo_vencimento', sa.Date(), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('pk_negociacao')
    )
    op.create_table('b3_posicao_acoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('conta', sa.Integer(), nullable=True),
    sa.Column('codigo_negociacao', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('codigo_isin', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('escriturador', sa.String(length=200), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_disp', sa.Integer(), nullable=True),
    sa.Column('quantidade_indisp', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('preco_fechamento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_atualizado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b3_posicao_emprestimos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('instituicao', sa.String(length=200), nullable=True),
    sa.Column('natureza', sa.String(length=100), nullable=True),
    sa.Column('num_contrato', sa.String(length=100), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('opa', sa.String(length=100), nullable=True),
    sa.Column('liquidacao_antecipada', sa.String(length=100), nullable=True),
    sa.Column('taxa', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('comissao', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('data_registro', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_fechamento', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valor_atualizado', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b3_proventos_recebidos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('tipo_evento', sa.String(length=200), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('b3_reembolso_emprestimos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('produto', sa.String(length=500), nullable=True),
    sa.Column('tipo_evento', sa.String(length=200), nullable=True),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_pregao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('b3_reembolso_emprestimos')
    op.drop_table('b3_proventos_recebidos')
    op.drop_table('b3_posicao_emprestimos')
    op.drop_table('b3_posicao_acoes')
    op.drop_table('b3_negociacao')
    op.drop_table('b3_movimentacao')
    op.drop_table('b3_bonificacao_acoes')
    # ### end Alembic commands ###
