ms_teams:
  url: "https://outlook.office.com/webhook/WEBHOOK_URL"
  title: TITLE
  message: >
    ROUTINE: {}
    \n \n \t - Executed at: {}.
    \n \n \t - Operator machine: {}
    \n \n \t - Operator ID: {}
    \n \n \t - Evidence available at: {}
    \n \n \t - Logs available at: {}
    \n \n \t Regards,
  bool_print_message: False
